### PR TITLE
Require user to specify which columns to flatten. Resolves #20

### LINKED ISSUE #20: Require user to specify branches he wants to flatten
The optional argument `flatten=True` causes root_pandas to flatten out array-like branches in the root file by increasing the number of events in the tuple.

This can lead to unexpected side effects if more than one branch of the TTree contains arrays.

It also fails and causes an error if there are two branches with arrays of unequal length or if one branch contains tensors of dimension two or higher.

The proposal is to only flatten the branches which are specified. The remaining non-scalar branches will then be dropped just as in the case when flatten=False.

### PR DESCRIPTION
**Pull request by KonstantinSchubert**

### CODE REVIEW

**Comment by KonstantinSchubert** [comment]
Do you think the duplicate code is an issue and how would I go best about avoiding it?

**Comment by KonstantinSchubert** [comment]
Maybe I should place the code which switches between old and new behaviour into the do_flatten function?

**Comment by ibab** [comment]
Thanks, could you add a test that shows what should happen if multiple columns are specified in the `flatten` option?

**Comment by KonstantinSchubert** [comment]
Should I do this in a new function test_flatten_multiple ?

**Comment by KonstantinSchubert** [comment]
If  you specify which  columns you want to flatten, numpy's stretch seems to silently(!) drop the columns which are array-like and not listed as to-be-flattened.

**Comment by KonstantinSchubert** [comment]
I am now passing both

**Comment by KonstantinSchubert** [comment]
Force push after rebase. Should now work as expected.

**Comment by ibab** [comment]
Excellent, this makes much more sense than the boolean flag and I like the implementation 👍

**Comment by KonstantinSchubert** [comment]
http://i3.kym-cdn.com/entries/icons/original/000/010/809/happy-oh-stop-it-you.png

**Pull request merged**
